### ISSUE TITLE
I get hits that are both in core.ignoredNames" and fuzzy-finder.ignoredNames AND .gitignore

### ISSUE THREAD

**Issue by hedefalk** [atom/fuzzy-finder#140]
I have tried everything to get rid of hits in the build output folder "target". It's .gitignored.

In core settings:
```
core.ignoredNames: [
      ".git .ensime_cache .settings .idea .target .cache-main .cache-tests target"
    ]

  "fuzzy-finder":
    ignoredNames: [
      ".idea .target target"
    ]
```

Also

exclude VCS Ignored Paths is checked so no settings for this in config.cson (since default right?).

But I still get stuff from target. How can this be?

<img width="254" alt="screen shot 2015-09-16 at 09 31 49" src="https://cloud.githubusercontent.com/assets/116520/9898926/b46f07e0-5c56-11e5-8814-cc3dfe4e4304.png">
<img width="697" alt="screen shot 2015-09-16 at 09 32 38" src="https://cloud.githubusercontent.com/assets/116520/9898932/bb044cbe-5c56-11e5-9af4-26adf1149b67.png">
<img width="334" alt="screen shot 2015-09-16 at 09 34 03" src="https://cloud.githubusercontent.com/assets/116520/9898934/bd8cfd46-5c56-11e5-9714-33ac9594376d.png">
<img width="205" alt="screen shot 2015-09-16 at 09 39 26" src="https://cloud.githubusercontent.com/assets/116520/9898948/dad1bfe0-5c56-11e5-9f2b-517902817ac0.png">

**Comment by izuzak** [comment]
@hedefalk Can you try separating path elements with a `, ` instead of with just a space? Notice that this is how settings show you paths ignored by default:

<img width="687" alt="screen shot 2015-09-16 at 13 47 03" src="https://cloud.githubusercontent.com/assets/38924/9903802/920aab6e-5c79-11e5-9236-cbff1fdbadad.png">

Try using that for ignored names in fuzzy finder and core settings.

If that doesn't help, can you post a link to the repository in question and your full config.cson file?

**Comment by hedefalk** [comment]
Oh, that was easy :+1: 

Wonder where I got that space separated list from. Would have "default guessed" `,` so I'll blame some unspecified misinformation I must have gotten at some point :)
