### ISSUE TITLE
Latest opened buffers list with cmd+t

### ISSUE THREAD

**Issue by gimenete** [atom/fuzzy-finder#16]
Hi,

Like SublimeText2 it would be cool to show a list of latest opened buffers when pressing `cmd+t`. It is very useful to quickly navigate to the previous edited file doing the following steps:
- `cmd+t` and it shows the list of latest opened buffers
- arrow down
- enter

That's the way I like to navigate to files that I know are opened because I've been working with them seconds or few minutes ago.

**Comment by timhaines** [comment]
@kevinsawicki great to see you added the last active path to the top of the list.  Thank you.

I'd like to propose this issue is reopened.  

It would be great if cmd-t could behave like cmd-b until the first key is pressed in the search box.  

I often switch between 3 or 4 files, and it would be super convenient (and what I'm used to coming from Sublime) if the default list of files was the list of latest opened buffers.  i.e. 10+ latest instead of only 1 latest.
