### ISSUE TITLE
is this the correct fuzzy logic or not ?  if now , how to make it work, coz i installed it. 

### ISSUE THREAD

**Issue by jpca999** [atom/fuzzy-finder#292]
![image](https://cloud.githubusercontent.com/assets/1026325/25557242/c5e4f1ae-2cdb-11e7-969f-e43636e8e494.png)

**Comment by 50Wliu** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:
