### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, lstat 'C:/Users\askochypets'

### ISSUE THREAD

**Issue by askochypets** [atom/fuzzy-finder#307]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.5.8

### Stack Trace

Uncaught Error: EPERM: operation not permitted, lstat 'C:\Users\askochypets'

```
At fs.js:982

Error: EPERM: operation not permitted, lstat 'C:\Users\askochypets'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at Proxy.realpathSync (fs.js:1657:19)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:316:29)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:21:27
    at Array.map (native)
    at Object.startTask (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/path-loader.js:19:52)
    at Object.startLoadPathsTask (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:119:45)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/fuzzy-finder/lib/main.js:33:30
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:14.7.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-bugs-syntax 1.9.3 
atom-bugs-ui 1.8.4 
atom-ternjs 0.18.2 
auto-detect-indentation 1.3.0 
autocomplete 0.47.0 
autocomplete-modules 1.6.9 
docblockr 0.9.4 
emmet 2.4.3 
file-icons 2.1.3 
git-blame 1.0.1 
hyperclick 0.0.40 
javascript-snippets 1.2.1 
js-hyperclick 1.11.0 
one-o-eight-syntax 0.28.2 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
```

**Comment by rsese** [comment]
Thanks for taking the time to contribute!

This looks pretty close to https://github.com/atom/fuzzy-finder/issues/289 so I'll go ahead and close as a duplicate. You may want to subscribe there for updates and if you can let us know if the error is reproducible for you in safe mode (`atom --safe`), that would be helpful.  

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).
