### ISSUE TITLE
Atom Failed to Find file in entire project file of Laravel

### ISSUE THREAD

**Issue by putuoka** [atom/fuzzy-finder#332]
i try to find file name DB.php located on \my laravel folder\vendor\laravel\framework\src\Illuminate\Support\Facades\DB.php but atom fail to search it using CTRL + P Any idea why?

**Comment by rsese** [comment]
Thanks for reaching out!  I'd suggest checking if your project has a `.gitignore` that ignores `vendor/` maybe?  Or double check your `Settings > Core > Ignored Names` setting as well.

If that doesn't help, feel free to post on the [message board](https://discuss.atom.io/) and mention me (@rsese) and we can take a look.

---

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by putuoka** [comment]
Hi @rsese thank you for replying. yes it's contain .gitignore but in my logic that file isn't related to atom or this fuzy finder. it just file for git (app) to ignore the folder to be upload to remote repository. i have checked core setting as well and there's still in default and no vendore folder included. could you please help why i can't find file DB.php inside folder vendor among many sub2 folder inside it?

**Comment by rsese** [comment]
> yes it's contain .gitignore but in my logic that file isn't related to atom or this fuzy finder.

Thanks for confirming - Atom will ignore files in your .gitignore by default for functionality like fuzzy finder but you can disable this in your settings at `Settings > Core > Exclude VCS Ignored Paths`.  If that doesn't help, please share your `.gitignore`.

**Comment by putuoka** [comment]
its work thanks @rsese you the best
