### ISSUE TITLE
Slow. 

### ISSUE THREAD

**Issue by tlorens** [atom/fuzzy-finder#348]
### Description
I've removed Symfony folders and only included folders that I edit files in.  Finder is OMG slow.  It appears to 'index' files, but that doesn't seem to speed things up any.  Typing is like running through water. 

**Expected behavior:** More real-time listing of matched files. 

**Actual behavior:** Typing is delayed and slow. 

**Reproduces how often:** 100%

### Versions
MacOS High Sierra 10.13.4
Atom    : 1.27.0
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.27.0
python 2.7.14
git 2.17.0

**Comment by thomasjo** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by tlorens** [comment]
Uh yeah, I followed your template.  Try again.

**Comment by lee-dohm** [comment]
@tlorens your comment was deleted as a violation of the [Atom Code of Conduct](https://github.com/atom/atom/blob/master/CODE_OF_CONDUCT.md) as it was insulting or derogatory. You may consider this an official warning.
