### ISSUE TITLE
Copy full path in the dialog

### ISSUE THREAD

**Issue by jefferyyuan** [atom/fuzzy-finder#393]
### The use case: move a file to another folder
Now we do the following steps:
- we want to move a file(original file) to another folder(dest folder): we first need to know the full path of the other folder. 
- We can use the finder to find the folder or a file in the dest folder, open the file, then get its full path.
- Then back to the original file and use F2(rename) to move it to the dest folder by change the path.

### Expected
- It would be great at the dialog(ctrl+t(or p)), when we select the file, we can copy its full path.
- So we don't have to open that file, get its path then close it.

**Comment by rsese** [comment]
Thanks again for the suggestion! Though I can see how useful this could be for some specific workflows like the one you described, as mentioned in the issue template the team is unlikely to work on new functionality right now.  Additionally, it's not something quite within the scope that we have have envisioned for this package but it could make a neat community package e.g. see this community package:

https://atom.io/packages/zsy-fuzzy-finder

It provides a fuzzy finder command that copy/pastes the file path rather than opening the file.

For these reasons and because we're trying to keep only tasks that need to be worked on in the issue list, I'm going to close the issue but thanks again for the feedback.
