### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sendCrawlEvent' of undefined

### ISSUE THREAD

**Issue by lacasta** [atom/fuzzy-finder#396]
[Enter steps to reproduce:]

1. When opening the Atom editor I get this error
2. Found related issues but were closed with no comments.

**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.13.1

### Stack Trace

Uncaught TypeError: Cannot read property 'sendCrawlEvent' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:31

TypeError: Cannot read property 'sendCrawlEvent' of undefined
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:31:25)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:36910
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:38272
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1174290)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1175731)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:37385)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-dark-fusion-syntax 2.2.1 
atom-eclipse-syntax 0.0.6 
atom-ide-debugger-node 0.7.3 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-ui 2.1.3 
atomic-rtags 1.3.0 
autocomplete-clang 0.11.5 
autocomplete-cmake 0.3.1 
autocomplete-ctags 0.4.1 
autocomplete-python 1.14.0 
autocomplete-xml 0.11.0 
build 0.70.0 
build-cmake 0.12.0 
busy-signal 2.0.1 
clang-format 2.0.8 
docblock-python 0.14.1 
file-watcher 2.0.0 
ide-clangd 0.4.0 
ide-cpp 0.1.0 
ide-python 1.4.1 
intentions 1.1.5 
language-autotools 2.0.1 
language-cmake 1.1.0 
language-common-lisp 0.9.5 
language-cpp14 0.6.2 
language-latex 1.2.0 
latex 0.50.2 
latex-autocomplete 1.1.1 
linter 2.3.0 
linter-clang 4.1.2 
linter-markdown 5.2.7 
linter-python 3.1.2 
linter-ui-default 1.7.1 
monokai 0.24.0 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
python-indent 1.1.7 
python-tools 0.6.9 
seti-syntax 1.2.0 
seti-ui 1.11.0 
switch-header-source 0.33.0 
symbols-tree-view 0.14.0 
```

**Comment by rsese** [comment]
Thanks for the report!  Can you confirm if you see this error when starting in [safe mode](https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?

**Comment by lacasta** [comment]
I am not getting the message any more. I added Thumb.db to the list of ignored files and I am not getting this anymore. I tried emptying the list, but still quiet. I do not remember having done anything else to cure it... Is there any way of resetting the config to check whether this had some influence ?

**Comment by Arcanemagus** [comment]
You can launch Atom with an [`ATOM_HOME` environment variable](https://flight-manual.atom.io/using-atom/sections/basic-customization/#custom-home-location-with-an-environment-variable) defined in order to temporarily use an alternative storage location.

Do you have any more information on how to trigger this?

**Comment by cheeren** [comment]
I also have this error, but I"m not sure what to do.

Occurs upon opening any project.

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [fuzzy-finder](https://github.com/atom/fuzzy-finder) package 1.13.5


### Stack Trace

Uncaught TypeError: Cannot read property 'sendCrawlEvent' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzy-finder/lib/path-loader.js:31

TypeError: Cannot read property 'sendCrawlEvent' of undefined
    at /app.asar/node_modules/fuzzy-finder/lib/path-loader.js:31:25)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:36910
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:38293
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208024)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:37394)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-python 1.14.1 
busy-signal 1.4.3 
city-lights-syntax 1.1.8 
file-icons 2.1.33 
kite 0.165.0 
linter 2.3.0 
linter-flake8 2.4.0 
linter-ui-default 1.7.1 
material 2.2.0 
minimap 4.29.8 
python-autopep8 0.1.3 
remote-ftp 2.2.0 
script 3.18.1 
switch-header-source 0.32.0 
vim-mode-plus 1.34.0 
```

**Comment by Arcanemagus** [comment]
Neither of you have answered the question [asked earlier](https://github.com/atom/fuzzy-finder/issues/396#issuecomment-498403490), but this sounds like an issue caused by a community package.

You two have the following common packages installed:
```
autocomplete-python 1.14.1 
busy-signal 1.4.3 
linter 2.3.0 
linter-ui-default 1.7.1 
switch-header-source 0.32.0 
```

The most suspicious sounding in the list to me is `switch-header-source`, however until you test in Safe Mode we can't really begin to guess.

**Comment by lacasta** [comment]
Hi,

Sorry for the silence. 

I am not able to reproduce the error anymore. I did try in safe mode as suggested and the problem did not appear. I guess it is as you say, one of the packages we have in common. In my case there are newer versions of some of them

busy-signal 2.0.1
switch-header-source 0.34.1

Many thanks !!


—
Carlos Lacasta

**Comment by Arcanemagus** [comment]
Thanks for responding!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

For anyone that is still able to reproduce this we would need you to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue with the problematic package.
