### ISSUE TITLE
Preview selected files in list

### ISSUE THREAD

**Issue by garand** [atom/fuzzy-finder#5]
![filepreview](https://f.cloud.github.com/assets/82437/1686763/05a6fd36-5dec-11e3-8050-dcb67400d621.gif)

In ST3, when filtering through the files in their fuzzy finder, the editor displays the contents of the file temporarily so you can peek into them without opening them. This would be an awesome feature to have as it can be helpful when trying to nail down exactly which file contains what you're looking for.

**Comment by drewbrokke** [comment]
+1

**Comment by lee-dohm** [comment]
This feature is now available using the "Preview Tabs" feature. You can go into the Settings View, navigate to the tabs package settings and check "Use Preview Tabs":

![screen shot 2015-06-05 at 8 46 14 am](https://cloud.githubusercontent.com/assets/1038121/8009694/61b1c5e4-0b5f-11e5-9a18-91e2419bbe1a.png)

**Comment by garand** [comment]
![giphy](https://cloud.githubusercontent.com/assets/82437/8009791/3216fa38-0b79-11e5-92fd-b194d9f9c101.gif)

**Comment by mnquintana** [comment]
Actually @lee-dohm I think this request is slightly different from Preview Tabs as currently implemented – in the initial screenshot, files are previewed as they're selected in the fuzzy-finder, which currently isn't implemented.

**Comment by lee-dohm** [comment]
Ah ok. Thanks for catching that. Still ... progress.

**Comment by mehcode** [comment]
@mnquintana I'd agree. And this looks far easier for a quick PR now that Preview Tabs are implemented.

**Comment by garand** [comment]
![tumblr_m0tq0c3odq1qe6dvp](https://cloud.githubusercontent.com/assets/82437/8009933/1c01b232-0b7a-11e5-8110-c043f1b1b259.gif)

**Comment by lucasfcunha** [comment]
+1

**Comment by garethweaver** [comment]
+1

**Comment by jwuwork** [comment]
Submitted a pull request #113 for this.  Enjoy! =)

**Comment by maahd** [comment]
+1

**Comment by otang** [comment]
+1

**Comment by jcraigk** [comment]
+1

**Comment by josue** [comment]
LGTM 👍 :shipit:  

This feature is all that's stopping me from switching to Atom. Wish this could be merged in soon.

**Comment by sksea** [comment]
+1

**Comment by skqr** [comment]
👍 🎏

**Comment by coolbox** [comment]
+1

**Comment by adamhutch** [comment]
+1

**Comment by anotheredward** [comment]
+1

**Comment by dabou** [comment]
:+1:

**Comment by wprater** [comment]
fuzzy finder and tabs are still lacking in comparison to ST3.  is there an API they both use to query recently selected files?

**Comment by pcnate** [comment]
This is incredibly useful in ST3. I frequently use this to find the correct file that has a similar name because I could type in a partial path / filename match, then arrow through the list and if I hover over the text I could scroll down and see if this file contains some obscure code that I otherwise cannot find without some trial and error searching of the project folder. Many other features can be added through packages but it looks like this cannot be so easily.

**Comment by brandonk3nt** [comment]
👍

**Comment by ackramer** [comment]
+1

**Comment by cklimkowsky** [comment]
+1

**Comment by rammandadapu** [comment]
+1

**Comment by pinzer** [comment]
+1

**Comment by sPaCeMoNk3yIam** [comment]
+100_000

**Comment by mintyPT** [comment]
+1

**Comment by oolongbrothers** [comment]
+1

**Comment by tgomesfork** [comment]
+1!

**Comment by d3adc0d3** [comment]
+1

**Comment by iamrauu** [comment]
+1 .. sadly its the main thing holding me back from switching to atom.

**Comment by cannjeff** [comment]
+1

**Comment by slikk66** [comment]
So while ago searching for this, found this repo which seemed to be perfect, but didnt work for me: https://github.com/toshi-saito/fuzzy-finder

I forked it and did a bit of tweaking with @captin411 and we got it working on Atom 1.19.0

I have no idea how to get this into a real plugin, and don't have time to add all the testing but maybe someone else does.

I think we broke the "git" stuff, specifically the ignored items (whatever those do, I dont know for sure) but the fuzzy preview works great

Steps:
- Install "fuzzy-finder-plus" package, it's still available in Atom
- Disable "fuzzy-finder" default installed package
- Download my repo fork here: https://github.com/slikk66/fuzzy-finder
- Copy the contents of /lib from my fork into your plugin directory of Atom, on my machine this is: /Users/YOUR_NAME/.atom/packages/fuzzy-finder-plus/lib/
- Restart Atom

http://imgur.com/a/QwpXJ

**Comment by neilthawani** [comment]
I have opened a PR at https://github.com/atom/fuzzy-finder/pull/313 to address this.

**Comment by mono424** [comment]
+1

**Comment by A7rMtWE57x** [comment]
+1

**Comment by pabloleone** [comment]
I was moving to Atom, but after finding this thread, I will say bye Atom and sorry to Sublime! Atom, was a pleasure!

**Comment by lee-dohm** [comment]
Upon reviewing with the team today, we've decided that we don't want to own this functionality because of the various performance and stability impacts that it could have on the fuzzy-finder package. For example, what if you type some characters or select files that match the data files in a particular directory that are 5GB each? For this reason, we're not going to accept this PR and we're closing the related issues.

However, we did discuss the possibility of someone creating a [provided service](https://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/) that could allow other community packages to integrate with fuzzy-finder to provide this behavior. We would be open to reviewing an [RFC](https://github.com/atom/atom/blob/master/docs/rfcs/000-template.md) for a design of this proposed service in atom/fuzzy-finder. If anyone is interested in working on this, please open a new issue for the RFC for review by the maintainer team.
