### ISSUE TITLE
Can't find markdown-preview in Atom command palette

### ISSUE THREAD

**Issue by mark-hahn** [atom/fuzzy-finder#85]
If I use `markdown preview` the command is found.  If I use the real name of the package, `markdown-preview` nothing is found.  May I suggest changing all dashes to spaces before searching?

**Edit:** Would you take a PR for this?

**Comment by izuzak** [comment]
Thanks, @mark-hahn. Can you reopen this over at https://github.com/atom/command-palette? 

Also, before opening a PR, it's always helpful to describe the motivation for the change in the issue -- e.g. why are you entering the name of the package with dashes in the first place? That should help everyone understand the problem and help them feel more confident that the change we're making is the right one. 

I'm guessing that you'd like to be able to copy/paste a command in its non-humanized form (eg. `fuzzy-finder:toggle-file-finder`) into the command palette and see it matched. Because the `-` characters are not ignored, the command is not matched in command palette. Ignoring dashes would make it easier to execute commands by copy/pasting them from somewhere else.

**Comment by mark-hahn** [comment]
FWIW: the reason that I often type in a dash that after typing package
names into apm my brain thinks that the name has the dash.  It sees
my-package which is nothing like "my package".  This comes from using
command lines in general.  A space is always a param separator.  Also my
brain usually types of lot of the package name even though less chars would
do.  I don't watch below while I'm typing above.
